sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: aeJM6xSdegpNU869DHUdvrtBg0QZiUzJM72LQxs+OlbEZog7WvpJuikOIAloedBwerqHsuH49PT4oe4UF/Dl9GAVL7S7XdZuQnWFVEQFN1vM8A3Po8OuwR6MgeB/mBUxK2C7pdHhf9liNfI67znapZzNevKaigDEfepAchpP86WtRg/GA81N7i11AKuanDIMWtrKxSrbbNI42E46OyhqqEwdSGp0SozAWlOHiARngSWJV6NyR7tEMYwFMaqhot7VcJBx/mRPkZwpv2r5qd+a2ZkM8KP2Lq3fjFgv+EIaCOirNDjSP9NuLNql7nifiojtm6lxBzp3klu4YDOHwBSMrpwyhnKU4UJiavq58wHsxcqT+TcU0p8geK2f1SOV3cqwMNfaUFgX3S6Z292BPkGlO5vZpLvxVj7dYUoSbA2MmED6Z1C0/u7r+k38sJZoihLoIhbGZ234sHKEg760VKygng8HvUjG/DwaHeFNUIpTeai4/fnVGgTkeom5rAfOdrWhRJeNMuV0HlCnImke0fcjKHStI9a3sXX4kY2utoknJjWytiFkLJ8u7fTf4AmStDJuw8FBfZ/Yek5+k5yHO2BOR3pgqq3Hoxu/hnQqg8+gK0LSNEOmGwyhWwx7dflg6TBIMqXUxg65OXjPqTbOygOY9GyjBXYGlfSF1hrC3fIxo0E=
  - secure: UHagrWFZx4hYREGGfa3qKuOdI+j3+Mwlw6dKgTa4xSIj/c3CwySPyeWihCBigE8FLUiFAUeIx6YxFK0POYv/2j9JnyXsNX5IilLBfliGjAyHcjypGD4JjhNH5ScSNb0r+MyAyVy9utjr1LOuD+JuNF1zylXQoRcOMFqhMnaWbpAHcd3HLEkhc/8SHGHhcgiHrLG+pRZtNbDYBo2XvKSTkut/VxUJU7jrcidOESOxS6ES0vcQlHubo7ZIa1XwsODU7XewKIcT2yKyBZo6CSYLZ4dOzC7jd7P9y/AOlilxInFHZdCgZfAVmlOd0U8jkNd8g0gGASaTL56u9HEy00fRpNaGd9skLDE1ZPK0OzUBVWJrLXnRpVNoc/S8ABv4WoAiQCIBEJSEw6uxAA8k/SngQYvmXoZgj2RPg+c+aozKsz46mmLBmesDmuitGVWs6wgm8g0qDDhTv8boupMZZhviY0q0Oib9f6Ti7Ev7Ew4B07AVvXEdcrQeEbPyeURLo2U+x1rtJKH4wWTqTF2h0ts35B0Mi0x4j5btHwXC6DCkdiHVjEM8532f7bpkuESZxgxSvKDZJ5m50Hu8zRNRIPUtRlPEWje8ewig0mttb62bclGSpfTLQ1Yr2Bjr+ZCJ/xM7pLoHNGbHo/JfUHGjPgfr3HczFYM1mP6lRNhKJxVo9mg=
  - secure: c59VdJMGaCFR5wc+mvlu/R7Zr31oIWq8+U85c1fCmDBX1j7+m1JMrx3Wi5n4XMlRNLygFm5srrGHm7ZhS3sX8F3zqESsH7vtOybp+B3NtJsfyEu7u6HjO2o7dTu278kAEY3axB1knKCtBeBXbO4J0H03wAH+sDYNTCfetCZh36KPxvgBPcbMSTtdsH6QwdEWePBwOgtHcCU4ox6fnAT82e/vzSz1iXkM7j5FDyHiLQhoH47g53an5LIYgEa1Y4Cc57vXT5ytrIuh1GMJ1OcgW9ikNDV9pS/1gDgaae7rL54IC4tbaZhuHe4mqUeyd+9F+vcR/7LJvfay+mI3/tBHhOqtu3snSLFKQpX1p5ZDBqC05khJAxbH/t9CyrkAqqLsp2hIQE5/33957M16tCwVozjj/7J8boqM1xgw72LxkvZRQj8TqFuK/vwqNgZrqawpCFxGXp9dHI2UwFESvgmjCgSDJvJ91mC7DId+vFOqu/jec4yLtiEOZmpk46fvLHk9NNhGzyRJgyJ5DR+z2QDRjk04qq++NZSbAEyXKBfxp8w99yGOaggp7CEdq7yapS0HdK4eFvqilXBSjRCCtjCjVFnwrj9Y8afciOBuVpKM6pYAErcAggbRfc4v5O7UklPOx2t9qYusovalm8tYw8qgUonz6Q1+RtKy46C5QoszKZw=
  - secure: egVxHVxtHdIMMZPujPef0PiBDJxL9CtyAfMEKq7CFk/ikHEdBG/zXA9PNLYUhlh/mUZ6Mk63eT8pEbJqhwgaDxnu4wYwzfYXdICJdpp51OVJrnpCOetD456yNa8w7I+hE7T60v2lPqZDynAP9JP2d9JiMjINcpD+4B8z1pDmNNEMDu0+bOBjR/naQ27HTfC3oFN1/VsbLW7xp5i6k3KqJpOo4N/jyX/B1XA1dRXM6fxLSM3/wbuuAXLBE891/MLQ3LBudSe3P4QtQi/M9C5w0BQ50QPXvgjcUzOD7cfXtSu770+ry2jd6be8n+hvvgvvC4IVAdH+TzJfwDzucwq0vxYHC+HDuhBFdsAuK9AtbBeziJQaf6SVfAlzaY/IP5yzPf1n1iS82Bt/HeN37NRDltoaopPSe8IYChYFJ2tG7HB7o+e12Fs1tYXCtgHpK98f0feKECq4UnwN0w85IaK7LLekTX5yDFrk5tSmSJi/V/svnOCLwf/WF7SowpyNT30Vmu00YYrnAk6q/7oxRooC4FFpYTgDCsIvXgkBIUBcFM2wBbzvY981sokDTXgqDO7vShwHV7R2xNbx9J+7XHDk4bOINusqK569naA8bGJ2F+mFvEe1hL0CN/z7CSZT/d9SEfWu6ufkRFRRK6lGKQ3mWY9brw2BvqAgX4LL0VglD/k=
